/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
// static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
    // 1. 从链接器脚本中导入 SDRAM 堆的起始和结束地址
    extern uint8_t __sdram_heap_start__; /* Symbol defined in the linker script */
    extern uint8_t __sdram_heap_end__;   /* Symbol defined in the linker script */

    // 2. 定义一个静态变量，用于跟踪当前堆的“栈顶”
    //    它只在第一次调用时被初始化为堆的起始地址
    static uint8_t *heap_end = NULL;
    uint8_t *prev_heap_end;

    if (NULL == heap_end)
    {
        heap_end = &__sdram_heap_start__;
    }

    // 3. 记录当前的堆顶，作为本次分配内存的返回值
    prev_heap_end = heap_end;

    // 4. 检查是否有足够的剩余空间
    if (heap_end + incr > &__sdram_heap_end__)
    {
        // 空间不足，返回错误
        errno = ENOMEM;
        return (void *)-1;
    }

    // 5. 空间足够，移动堆顶指针
    heap_end += incr;

    // 6. 返回本次分配的内存块的起始地址
    return (void *)prev_heap_end;
}

#if defined(__PICOLIBC__)
  // Picolibc expects syscalls without the leading underscore.
  // This creates a strong alias so that
  // calls to `sbrk()` are resolved to our `_sbrk()` implementation.
  __strong_reference(_sbrk, sbrk);
#endif
